batch_size: 32
seq_len: 100
motor_neurons: 2
# conv head params
lr: [1e-3]
n_conv_layers: [3]
base_kernel_size: [5]
# ncp params
inter_neurons: [12, 15, 18]
command_neurons: [9, 12]
sensory_fanout: [6]
inter_fanout: [6]
recurrent_command_synapses: [6, 8, 10]
motor_fanin: [4]